config/routes.rb
Rails.application.routes.draw do

  resources :relationships

  root 'pages#private'

  get 'posts/new'

  get 'posts/create'

  get '/sessions' => 'sessions#index'

  get 'sessions/new', as: :sign_in
  post "/sessions" => "sessions#create"
  delete "sessions" => "sessions#sign_out", as: :destroy_session





  get "private" => 'pages#private'
  get 'public' => 'pages#public'



  get 'private/posts/new' => 'posts#new', as: :new

  post '/posts' => 'posts#create'

  get '/posts/show' => 'posts#show'

  get '/private/posts' => 'posts#index'

  delete '/private/posts' => 'posts#delete'




  get '/users/new' => 'users#new', as: :users_new

  post '/users' => 'users#create'

  delete '/relationships' => "relationships#destroy"


  get '/talk' => 'pages#talk'

  get '/change_background_color' => 'pages#change'

  get '/adventure' => 'pages#adventure'

  get '/jokes' => 'pages#jokes'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  has_many :relationships
  has_many :friends, through: :relationships, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action only: :private do

    if session[:signed_in]
    else
      session[:return_to] = request.url
      redirect_to sign_in_path
    end
  end

  before_action  do
    @current_user = User.find(session[:user_id]) if session[:signed_in]
  end

  def public

    @posts = Post.order("create_at DESC").page(params[:page]).per(10)
    @users = User.all.includes(:posts)
  end

  def private
    @posts = Post.order("create_at DESC").page(params[:page])
    @total = 0
    @relationships = []
   Relationship.all.each do |relationship|
     @relationships << relationship if relationship.user_id == @current_user.id
    end

  end

  def talk
  end

  def change
  end

  def adventure
  end

  def jokes
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  before_action  do
    @current_user = User.find(session[:user_id]) if session[:signed_in]
  end

  def index
    render :delete
  end

  def new
    user = User.find(params[:user_id])
    @post = user.posts.new
  end

  def create

    @post = Post.new(post_params)
    @post.user_id = @current_user.id

    @post.create_at = DateTime.now
    if @post.save

      redirect_to private_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.order('create_at DESC')
    @relationship = Relationship.new(user_id: @current_user.id, friend_id: @user.id) if @current_user
  end

  def delete
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:tweet)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action do
    @current_user = User.find(session[:user_id]) if session[:signed_in]
  end

    def create
        @relationship = Relationship.new(user_id: @current_user.id, friend_id: params[:friend_id])

      if @relationship.save
          redirect_to relationship_path(@relationship)
      else
          flash[:error] = "Couldn't Follow"
          redirect_to root_url
      end
    end

    def show
      @relationships = Relationship.find(params[:id])
      redirect_to private_path
    end

    def destroy
      @relationship = Relationship.where(:user_id => @current_user.id,:friend_id => params[:friend_id])
      @relationship.first.delete

      redirect_to root_path, notice: "Unfollow successful"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    
  end
  def new
  end

  def create
    user = User.find_by username: params[:username]
    if user != nil && user.password == params[:password]
      session[:user_id] = user.id
      session[:signed_in] = true

      redirect_to session[:return_to], notice: "You Signed in"
    else
      render :new, notice: "Sign in fail"
    end
  end

   def sign_out
    session[:signed_in] = false
    session.delete(:user_id)
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)

    if @user.save
      session[:user_id] = @user.id

      session[:signed_in] = true

      redirect_to session[:return_to], notice: "You Signed in"

    else
      render :new, notice: "Sign up fail"
    end
  end


  private

  def params_user
    params.require(:user).permit(:username, :password, :photo_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_signed_in?
    @current_user.present?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Micropost</title>

  <link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>

  <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>



  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<div class="nav">
  <span class='home'><%= link_to "Home", root_path %></span>

  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_session_path, method: "delete" %>
    <% else %>
    <%= link_to "Sign In", sign_in_path %>
  <% end %>

  <%= notice %>
</div>
<div class="container">
  <div class="row">
      <%= yield %>
  </div>


</div>
</body>
</html>

app/views/pages/_game.html.erb
<h3 class="game">Game</h3>
<%= link_to "Talk to the web", talk_path %>
<%= link_to "Change Background ", change_background_color_path %>
<%= link_to "Adventure Story", adventure_path %><br>
<%= link_to "Jokes", jokes_path %>

app/views/pages/_profile.html.erb
      <%= image_tag @current_user.photo_url, class:"pic" %>
      <h4 class="username"><%= @current_user.username %></h4>
      <%= link_to "Create a post", new_path(user_id: @current_user.id) %><br />


      <%= link_to 'All the user', public_path(user_id: @current_user.id) %>

app/views/pages/adventure.html.erb
<div class="top-page"></div>

  <div class="top-page"></div>
    <div class="col-md-2 well" >
      <%= render partial: "profile" %>
  </div>





<div class="col-md-7 well">

  <div id="blank">
      <form>

        <div class="form-group has-error">
          <label class="control-label" for="person1">Your Name</label>
          <input type="text" class="form-control" id="person1" placeholder="Your name">
        </div>

        <div class="form-group has-error">
          <label class="control-label" for="person2">Another Name</label>
          <input type="text" class="form-control" id="person2" placeholder="Another name">
        </div>

        <div class="form-group has-error">
          <label class="control-label" for="animal">An Animal</label>
          <input type="text" class="form-control" id="animal" placeholder="An Animal">
        </div>

        <div class="form-group has-error">
          <label class="control-label" for="exclamation">An exclamation</label>
          <input type="text" class="form-control" id="exclamation" placeholder="An exclamation">
        </div>

        <div class="form-group has-error">
          <label class="control-label" for="verb">A past tense verb</label>
          <input type="text" class="form-control" id="verb" placeholder="A past tense verb">
        </div>

        <div class="form-group has-error">
          <label class="control-label" for="noun">A noun</label>
          <input type="text" class="form-control" id="noun" placeholder="A past tense verb">
        </div>

        <button type="submit" class="btn btn-default">Submit</button>

      </form>
    </div>


  <div id="story">
  <h1>A fantastical adventure</h1>
  <p>One day, <span class="person1"></span> and <span class="person2"></span> were walking through the woods, when suddenly a giant <span class="animal"></span> appeared.
    "<span class="exclamation"></span>", <span class="person1"></span> cried. The two of them <span class="verb"></span> as quickly possible, and when they were safe,
    <span class="person1"></span> and <span class="person2"></span> gave each other a giant <span class="noun"></span>.</p>
  </div>
</div>



  <div class="col-md-2 well game">
    <%= render partial: "game" %>
  </div>

app/views/pages/change.html.erb
<div class="top-page"></div>

  <div class="top-page"></div>
    <div class="col-md-2 well" >
      <%= render partial: "profile" %>
  </div>



<div class="col-md-7 well">
   <h1>What's your favorite color?</h1>
      <p id="red-border">Click a button to choose what color you'd like this page to be or <span class="clickable border">click here</span> for magic</p>

      <button class="btn btn-success" id="background-green">Green</button>
      <button class="btn btn-warning" id="background-yellow">Yellow</button>
      <button class="btn btn-danger" id="background-red">Red</button>
      <button class="btn btn-primary" id="original">Original Background</button>

</div>




<div class="col-md-2 well game">
  <%= render partial: "game" %>
</div>

app/views/pages/jokes.html.erb
<div class="top-page"></div>

  <div class="top-page"></div>
    <div class="col-md-2 well" >
      <%= render partial: "profile" %>
  </div>



<div class="col-md-7 well">

  <h2>Click on button to select the subject</h2>
  <button class="btn btn-success" id="marriage-button">marriage</button>
  <button class="btn btn-warning" id="college-button">college</button>
  <button class="btn btn-danger" id="parent-button">parent</button>
  <button class="btn btn-primary" id="cop-button">cop</button>


   <div id="marriage">

    <h3>marriage</h3>
    <p>Husband takes the wife to a disco. There’s a guy on the dance floor giving it large – break dancing, moonwalking, back flips, the works. The wife turns to her husband and says: "See that guy? 25 years ago he proposed to me and I turned him down." Husband says: "Looks like he’s still fucking celebrating!!"</p>
    </div>

  <div id="college">
    <h3>College</h3>
    <p>Mother: Come on victor you'll be late for school.</p>
    <p>John: Ahh mum do I have to, all the teachers hate me, and all the students hate me too.</p>
    <p>Mother: Yes you do.</p>
    <p>John: Give me a good reason</p>
    <p>Mother: You're 34 and you’re the Principal!</p>
      </div>

      <div id="parent">
        <h3>Parent</h3>
       <p>A: Just look at that young person with the short hair and blue jeans. Is it a boy or a girl?</p>
    <p>B: It's a girl. She's my daughter. </p>
    <p>A: Oh, I'm sorry, sir. I didn't know that you were her father. </p>
    <p>B: I'm not. I'm her mother.</p>
    </div>

    <div id="cop">
      <h3>Cop</h3>
      <p>A male driver is pulled over by a cop and the following conversation takes place</p>
      <p>Man: What's the problem officer?</p>
      <p> Cop: You were going at least 75 in a 55 zone.</p>
      <p>Man: No sir, I was going 65.</p>
      <p>  Wife: Oh Harry. You were going 80. (Man gives his wife a dirty look.) </p>
      <p> Cop: I'm also going to give you a ticket for your broken tail light.</p>
      <p> Man: Broken tail light? I didn't know about a broken tail light!</p>
      <p>  Wife: Oh Harry, you've known about that tail light for weeks.  (Man gives his wife a dirty look.) </p>
      <p> Cop: I'm also going to give you a citation for not wearing your seat belt.</p>
      <p>  Man: Oh, I just took it off when you were walking up to the car.</p>
      <p>  Wife: Oh Harry, you never wear your seat belt.</p>
      <p>  Man: Shut your mouth, woman! </p>
      <p> Cop: Ma'am, does your husband always talk to you this way?</p>
      <p>  Wife: No, only when he's drunk.</p>
    </div>


</div>




<div class="col-md-2 well game">
  <%= render partial: "game" %>
</div>

app/views/pages/private.html.erb
<div class="top-page"></div>

  <div class="top-page"></div>
    <div class="col-md-2 well" >
      <%= render partial: "profile" %>
  </div>

<div class="col-md-7 well">

  <% Relationship.all.each do |relationship| %>
    <% @total += 1 if relationship.user_id == @current_user.id %>
  <%end%>
  <h3>People <%= @current_user.username.capitalize %> FOLLOWING: <%=@total%></h3>

        <% @posts.each do |post| %>

          <% if post.user_id == @current_user.id %>
            <ul>
              <li>
                <%= image_tag @current_user.photo_url, class: "public-image" %>
                <%= post.tweet %>
                <%= post.create_at.strftime("%b %e, %l:%M %p") %>
                <%= link_to "Delete", private_posts_path(post.id), method: :delete, data: {confirm: "Are you sure?"} %>

            </ul>
          <%end%>



              <% @relationships.each do |relationship| %>

              <% if post.user_id == relationship.friend_id%>
              <ul>
                <li>
                  <%= image_tag post.user.photo_url, class: "public-image" %>
                  <%= link_to relationship.friend.username, posts_show_path(id: relationship.friend.id) %>

                  <%= post.tweet %>
                  <%= post.create_at.strftime("%b %e, %l:%M %p") %>
                  </li>
              </ul>
              <%end%>

          <%end%>

          
        <%end%>

  <%= paginate @posts %><br />
      </div>

<div class="col-md-2 well game">
  <%= render partial: "game" %>
  </div>

app/views/pages/public.html.erb
<div class="top-page"></div>

  <div class="top-page"></div>
    <div class="col-md-2 well" >
      <%= render partial: "profile" %>
  </div>


<div class="col-md-7 well">

  <h1>Hey <%= @current_user.username.capitalize %>. Recently Posts</h1>

  <% @posts.each do |post| %>

        <%= image_tag post.user.photo_url, class: "public-image" %>
        <%= link_to post.user.username, posts_show_path(id: post.user_id) %>
          <ul>
            <li>
              <%= post.tweet %>
              <%= post.create_at.strftime("%b %e, %l:%M %p") %>
            </li>
          </ul>
  <%end%>

  <%= paginate @posts %>
</div>


<div class="col-md-2 well game">
  <%= render partial: "game" %>
  </div>

app/views/pages/talk.html.erb
<div class="top-page"></div>
  <div class="col-md-2 well" >
    <%= render partial: "profile" %>
</div>


<div class="col-md-7 well">
    <h3>Talk to the web.</h3>
    <button type="button" class="btn btn-primary" id="hello">Say hello</button>
    <button type="button" class="btn btn-info" id="goodbye">Say GoodBye</button>
    <button type="button" class="btn btn-danger" id="stop">Say "Stop Copying Me"</button>

    <div class="row">
      <div class="row">
        <div class="col-md-5">
          <h4>You said</h4>
            <ul class="unstyled" id="user">
            </ul>
        </div>

        <div class="col-md-5 game">
          <h4>The web said</h4>
            <ul class="unstyled" id="webpage">
            </ul>
        </div>

      </div>
    </div>
</div>


<div class="col-md-2 well game">
  <%= render partial: "game" %>


  </div>

app/views/posts/new.html.erb
<h1>Post your new tweet</h1>

<%= form_for @post do |f| %>

  <%= f.label :tweet %>
  <%= f.text_field :tweet %>



  <%= f.submit "Post tweet" %>

<%end%>

app/views/posts/show.html.erb
<div class="top-page"></div>

<div class="col-md-2 well" >

      <%= image_tag @current_user.photo_url, class:"pic" %>
      <h4 class="username"><%= @current_user.username %></h4>
      <%= link_to "Create a post", new_path(user_id: @current_user.id) %><br />


      <%= link_to 'All the user', public_path(user_id: @current_user.id) %>

</div>


<div class="col-md-7 well">
  <%= image_tag @user.photo_url, class:"pic" %>

  <% @posts.each do |post| %>
    <% if post.user_id == @user.id %>
    <ul>
      <li><%= post.tweet %> on <%= post.create_at.strftime("%b %e, %l:%M %p") %></li>
    </ul>
    <%end%>
  <%end%>


  <% if !@current_user.friends.include? @user %>

    <%= button_to 'Follow', relationships_path(friend_id: @user.id) %>
  <%else %>
    <%= button_to 'UnFollow', relationships_path(user_id: @current_id, friend_id: @user.id), method: :delete %>
  <%end%>

  <%= link_to 'All the user', public_path(user_id: @current_user.id) %>

</div>


<div class="col-md-2 well game">

<h3>Game</h3><br />
<%= link_to "Talk to the web", talk_path %>
<%= link_to "Change Background ", change_background_color_path %>
<%= link_to "Adventure Story", adventure_path %><br>
<%= link_to "Jokes", jokes_path %>
</div>

app/views/users/new.html.erb
<div class="sign-in">
<h1>Please Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br /><br />

  <%= f.label :password %>
  <%= f.password_field :password %><br /><br />



  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %><br /><br />

  <%= f.submit "Create Account" %>
<%end%>
</div>